### ISSUE TITLE
建了个群讨论RL in Trading

### ISSUE THREAD

**Issue by xiaoyongzhu** [wangshub/RL-Stock#15]
非原作者，对RL in Trading比较感兴趣，建了个微信群。如果有兴趣的同学可以一起讨论。
![image](https://user-images.githubusercontent.com/1185090/79926807-b4fc9d80-83f2-11ea-836f-d45613463b29.png)

**Comment by WhoAmI233** [comment]
过期了，能再发一个吗

**Comment by CorePig** [comment]
过期了，能再发一个吗
